# Generated by Django 3.2.7 on 2021-09-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_expense_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemonth',
            name='trigger',
            field=models.IntegerField(null=True),
        ),
    ]
