# Generated by Django 3.2.7 on 2021-09-20 04:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_expensemonth_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('1.0'))]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='expense.category'),
        ),
    ]
