# Generated by Django 3.2.7 on 2021-09-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_auto_20210920_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
    ]
