# Generated by Django 3.2.7 on 2021-09-20 05:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_auto_20210920_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemonth',
            name='income',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.0'))]),
        ),
        migrations.AlterField(
            model_name='expensemonth',
            name='limit',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('1.0'))]),
        ),
    ]
