# Generated by Django 3.2.7 on 2021-09-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_auto_20210920_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemonth',
            name='income',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expensemonth',
            name='limit',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='expensemonth',
            name='trigger',
            field=models.IntegerField(),
        ),
    ]
