# Generated by Django 3.2.7 on 2021-09-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_auto_20210920_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemonth',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
