# Generated by Django 3.2.7 on 2021-09-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=10, null=True),
        ),
    ]
